
name: Android Emulator Workflow

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          ./ngrok authtoken $NGROK_AUTH_TOKEN
          ./ngrok tcp 3389 > ngrok.log &

      - name: Set up Android Emulator
        run: |
          docker pull scottyab/docker-android:29
          docker run -d --name emulator -e DEVICE="pixel" -e API=29 -e ABI="x86" scottyab/docker-android:29

      # Add more steps for your build and test processes

      - name: Keep workflow running
        run: |
          while true; do sleep 1; done

      # Clean up is not necessary since the workflow will run indefinitely
