name: Web App Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          ./ngrok authtoken 2QYwoAcWBJnRdBbzejjYxs008Mz_3pAVcAj1dvxadg2nAhGvp
          ./ngrok http 80 > ngrok.log &
          sleep 10

      - name: Set up Desktop Deluxe
        run: |
          docker pull kasmweb/desktop-deluxe
          docker run -d -p 8080:8080 kasmweb/desktop-deluxe

      - name: Display ngrok connection URL
        run: |
          echo "Ngrok connection URL:"
          curl --silent http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
