
name: Android Emulator Workflow

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          ./ngrok authtoken 2QYwoAcWBJnRdBbzejjYxs008Mz_3pAVcAj1dvxadg2nAhGvp
          ./ngrok tcp 3389 > ngrok.log &
          sleep 10 # รอให้ ngrok เริ่มต้นเชื่อมต่อ

      - name: Set up Android Emulator
        run: |
          docker pull secsi/dockerized-android-core-emulator-11.0
          docker run -d --name emulator -e AVD_NAME="pixel" -e PLATFORM_VERSION="11.0" -e ABI="x86" secsi/dockerized-android-core-emulator-11.0

      - name: Display ngrok connection URL
        run: |
          echo "Ngrok connection URL:"
          curl --silent http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: Keep workflow running
        run: |
          while true; do
            adb devices | grep emulator-5554
            if [[ $? -eq 0 ]]; then
              echo "Android emulator is awake."
              break
            fi
            sleep 1
          done

